[browser]
gatherUsageStats = false

[server]
headless = true
maxUploadSize = 200

[theme]
primaryColor = "#075b9e"
backgroundColor = "#f4f8fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#14263a"
font = "sans serif"

